<?php

namespace app\model;


use core\Model;

class IComment extends Model
{
    public function getTableName()
    {
        return 'icomment'; // TODO: Change the autogenerated stub
    }

    // 查询所有的评论，同时查询出评论对应的文章的文章的名字
    public function getList()
    {
//        $sql = "SELECT icomment.*, article.name AS article_name
//                  FROM icomment
//                  LEFT JOIN article
//                    ON icomment.article_id=article.id";
//          $sql = "SELECT icomment.*, article.name as article_name, user.username as user_name
//                    FROM icomment
//                    LEFT JOIN article
//                      ON icomment.article_id=article.id
//                    LEFT JOIN user
//                      ON icomment.user_id=user.id";
            $sql = "SELECT icomment.*, article.name as article_name, user.username as user_name, ic.content as reply_content
                      FROM icomment LEFT JOIN article ON icomment.article_id=article.id
                      LEFT JOIN user ON icomment.user_id=user.id 
                      LEFT JOIN icomment ic ON icomment.reply_id=ic.id";
        return $this->getAll($sql);
    }

    public function getICommentsByArticleId($id)
    {
        $sql = "SELECT icomment.*, user.username FROM icomment 
                  LEFT JOIN user ON icomment.user_id=user.id
                WHERE icomment.article_id={$id};";
        return $this->getAll($sql);
    }

    public function noLimitIComment($icomments, $replyId = 0)
    {
        $noLimitIComments = array();
        foreach ($icomments as $icomment) {
            if ($icomment['reply_id'] == $replyId) {
                // 可能有儿子评论
                $icomment['son'] = $this->noLimitIComment($icomments, $icomment['id']);
                $noLimitIComments[] = $icomment;
            }
        }
        return $noLimitIComments;
    }
}